services:
  - type: web
    name: psylocyba-license
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn server_render:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psylocyba-db
          property: connectionString

databases:
  - name: psylocyba-db
    plan: free
